version: "3.9"
services:
  app:
    image: learn_nest:v0.0.1
    env_file:
      - .env
    container_name: nest-server
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: "$DB_USERNAME"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_PASSWORD"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    links:
      - postgres

volumes:
  postgres:
    driver: local