version: "3.9"
services:
  app:
    image: learn_nest:v0.0.1
    env_file:
      - .env.development
    container_name: nest-server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres
    container_name: base_app
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.development
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.development
    links:
      - postgres

volumes:
  postgres:
    driver: local