###

POST  http://localhost:3000/auth/signup HTTP/1.2
Content-Type: application/json

{
    "email": "cuhieu04112002@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/auth/login HTTP/1.2
Content-Type: application/json

{
    "email": "cuhieu04112002@gmail.com",
    "password": "1234"
}

###

GET http://localhost:3000/auth/me
Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1aGlldTA0MTEyMDAyQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNCIsImlhdCI6MTY2ODQ0NDQ3NSwiZXhwIjoxNjY4NDQ0NTM1fQ.l-qqOA_mLlI5fKEaTDPcxwO_fcmomtF0Pd_lMOIdZZWZ2MWGPCCj7AiEIgZHREI2UKJOmNDJ4ez6DNUCgSVdTsJnkeWIGVd4nJVg2JKNjDcQyl77VVrjRY3s4481pDUCF3izKGCaVrGqoPDaKKH5epQkRse5AwPEB659oybNybqRIx5fvQdbl9LncMQLciOfLYR8oS5xh9Xxra__aZUAmd35wZmF4TBpGIlshb-Q_r0hmnieTqbF2PqEJCcaB4tB0-I6kOUb09g5cCe_UWUzm1cYcOKfX3Xp6D1bgoVhzw6ez-Hi-MqspVSLf8VpLvlgtrpw-6zTFf4jdoNhxR9vU3vgcPEgRN9-t6v3TXFptHJGQ_h0_B-0rS3A7rDBQ1S5q2pDDoECzGChuDs0MUwEFMsoNGLy16_IgZUc2HXfaVnBHaRR1gkLayRRj0Qtnn1txl8l7368-nEzqwjiKJrWNj3ln9v13F017UgQuyxDRfVtIpWx98n1CeVcUJOnVxH5pTam-ydPUci2wsvSTXhyJ73e9U5_swozkNhZ25RfQhh4c-69k0zgBeTQmT7idTJVPly8QPKbkW2GJfTRVcp-Tqhmh6jbeQIMBb-4tiSEf1Od4XbxTQYIrqbFQeIc_WVljXXpZZXqrO38aF-jSjnBC4a6-_2Pn8YfUK9FAkdsCY8"
Content-Type: application/json